### ISSUE TITLE
blog post a little unclear

### ISSUE THREAD

**Issue by lwhorton** [aroemers/clojure-cli-tools-build#1]
Hey @aroemers thank you very much for writing this neat [blog post](http://www.functionalbytes.nl/clojure/nodejs/figwheel/repl/clojurescript/cli/2017/12/20/tools-deps-figwheel.html?__s=pm63btqkz4hhoemsigv4). I was curious if I could drop boot / leiningen with 1.9's cli-tools, and this gets me well on the way. 

I wanted to point out some missing pieces that I think would make the blog post a little more clear:

- When you introduce a `with-namespaces` macro, you do not mention that the figwheel-sidecar namespace should be removed from the global require declarations. After thinking about it for a while this becomes obvious, but I initially tripped up here wondering "how does this macro possibly work if the other tasks aren't also using it?"

- Your cljs compiler options will not work unless you use exactly "src" for source files, which is pretty implicit. If your dirs look instead like `src/cljs` and `src/clj`, for example, figuring out that the cli-tools auto-provides `src` on the classpath, but nothing else, will be very confusing. You might want to make a note to include a difference `:paths [...]` config in the `deps.edn`  file.

**Comment by aroemers** [comment]
Hi @lwhorton,

Thank you for your feedback!

> When you introduce a with-namespaces macro ...

Good catch, I updated the blog post (not live yet, but will be visible in the next update).

> Your cljs compiler options will not work unless you use exactly "src" for source files ...

I agree that I skimmed over the part that we use `src` as our ClojureScript source directory. But, does adding `:paths [...]` in `deps.edn` work for the ClojureScript compiler?
