### ISSUE TITLE
Cannot get figwheel running; flesh it out a bit more?

### ISSUE THREAD

**Issue by KingMob** [aroemers/clojure-cli-tools-build#3]
The blog post and repo were just what I was looking for, for my new project, but I cannot for the life of me get figwheel running.

I created a matching `src/my_app/core.cljs`, and tried to set up `resources/public/index.html` and changed the output directories for figwheel so the index.html could find the js, but I keep getting "Figwheel Server: Resource not found" when I try to load the browser page.

Can you flesh out the skeleton so we can see what we're missing? Ideally, one should be able to go from `git clone` to `clj -R:repl build.clj figwheel` to `http://localhost:3449` and see it all working.

Thanks for the great post, btw!

**Comment by KingMob** [comment]
Found a bit of an answer on Slack: `resources` has to be in the `:paths` for Figwheel.

**Comment by aroemers** [comment]
Hi Matthew, 

Thank you for your kind words. Did you get it to work already? The current example is for use with a node.js project, so it would change the source somewhat.

Let me know. If you still have trouble, I'm happy to help.

**Comment by KingMob** [comment]
Thanks, I did end up getting it running with some help from https://github.com/PEZ/deps-edn-figwheel, which more closely aligned with what I was trying to do.
